source("functions/utils.R")
fixture <- tempfile("annotation-input-fixture-")
dir.create(file.path(fixture, "repositories", "BrainOmicsData"), recursive = TRUE)
dir.create(file.path(fixture, "data", "BrainOmicsData", "integration_25", "annotation"), recursive = TRUE)
saveRDS(
  data.frame(Cells = "a", CellType = "Astrocytes"),
  file.path(fixture, "data", "BrainOmicsData", "integration_25", "annotation", "celltype_assignments.rds")
)
setwd(file.path(fixture, "repositories", "BrainOmicsData"))
directory <- tempfile("annotation-input-test-")
dir.create(directory)
write_tsv(data.frame(Value = 1), file.path(directory, "result.tsv"))
write_annotation_input(directory, "result.tsv")
stopifnot(isTRUE(validate_annotation_statistics(directory)))
write_tsv(data.frame(Value = 2), file.path(directory, "result.tsv"))
stopifnot(isTRUE(validate_annotation_statistics(directory)))
write_annotation_input(directory, "result.tsv")
input <- read_tsv(file.path(directory, "annotation_input.tsv"))
input$Annotation_SHA256 <- "stale"
write_tsv(input, file.path(directory, "annotation_input.tsv"))
stopifnot(isTRUE(validate_annotation_statistics(directory)))
unlink(file.path(directory, "result.tsv"))
stopifnot(inherits(try(validate_annotation_statistics(directory), silent = TRUE), "try-error"))
write_tsv(data.frame(Value = 3), file.path(directory, "result.tsv.gz"))
stopifnot(identical(read_tsv(file.path(directory, "result.tsv.gz"))$Value, 3L))
cat("PASS: changed content and historical hashes accepted; missing files rejected; gzip TSV\n")
