sciencedb_expression_layout_version <- function() "2.0.0"

sciencedb_read_seurat_lines <- function() {
  c(
    "#!/usr/bin/env Rscript",
    "",
    "suppressPackageStartupMessages({",
    "  library(Matrix)",
    "  library(Seurat)",
    "  library(data.table)",
    "})",
    "",
    "args <- commandArgs(trailingOnly = TRUE)",
    "cmd <- commandArgs(FALSE)",
    "file_arg <- grep('^--file=', cmd, value = TRUE)",
    "script_file <- if (length(file_arg) > 0) normalizePath(sub('^--file=', '', file_arg[[1]])) else NA_character_",
    "package_dir <- if (length(args) >= 1) args[[1]] else if (!is.na(script_file)) dirname(dirname(script_file)) else getwd()",
    "package_dir <- normalizePath(package_dir, mustWork = TRUE)",
    "output_file <- if (length(args) >= 2 && nzchar(args[[2]])) args[[2]] else NA_character_",
    "dataset_arg <- if (length(args) >= 3 && nzchar(args[[3]])) args[[3]] else 'all'",
    "",
    "expr_dir <- file.path(package_dir, 'expression')",
    "manifest_file <- file.path(expr_dir, 'shard_manifest.tsv')",
    "metadata_file <- file.path(package_dir, 'metadata', 'metadata.tsv.gz')",
    "integrated_umap_file <- file.path(package_dir, 'embeddings', 'integrated_umap.tsv.gz')",
    "integrated_pca_file <- file.path(package_dir, 'embeddings', 'integrated_pca.tsv.gz')",
    "unintegrated_umap_file <- file.path(package_dir, 'embeddings', 'unintegrated_umap.tsv.gz')",
    "",
    "manifest <- read.delim(manifest_file, sep = '\\t', stringsAsFactors = FALSE, check.names = FALSE)",
    "required <- c('Dataset', 'Relative_Directory', 'Cells', 'Features', 'Nonzero_Values')",
    "if (!all(required %in% names(manifest)) || anyDuplicated(manifest$Dataset)) stop('Invalid expression shard manifest')",
    "selected_datasets <- if (identical(tolower(dataset_arg), 'all')) manifest$Dataset else trimws(strsplit(dataset_arg, ',', fixed = TRUE)[[1]])",
    "unknown <- setdiff(selected_datasets, manifest$Dataset)",
    "if (length(unknown)) stop('Unknown dataset(s): ', paste(unknown, collapse = ', '))",
    "manifest <- manifest[match(selected_datasets, manifest$Dataset), , drop = FALSE]",
    "",
    "read_shard <- function(row) {",
    "  shard_dir <- file.path(expr_dir, row$Relative_Directory)",
    "  counts <- ReadMtx(",
    "    mtx = file.path(shard_dir, 'matrix.mtx.gz'),",
    "    features = file.path(shard_dir, 'features.tsv.gz'),",
    "    cells = file.path(shard_dir, 'barcodes.tsv.gz'),",
    "    feature.column = 1, unique.features = TRUE",
    "  )",
    "  if (nrow(counts) != row$Features || ncol(counts) != row$Cells || length(counts@x) != row$Nonzero_Values) stop('Expression shard contract failed for ', row$Dataset)",
    "  counts",
    "}",
    "counts <- lapply(seq_len(nrow(manifest)), function(i) read_shard(manifest[i, , drop = FALSE]))",
    "names(counts) <- manifest$Dataset",
    "cell_order <- unlist(lapply(counts, colnames), use.names = FALSE)",
    "if (anyDuplicated(cell_order)) stop('Duplicated cells across expression shards')",
    "metadata <- as.data.frame(fread(metadata_file, sep = '\\t', check.names = FALSE, nThread = 4))",
    "rownames(metadata) <- metadata$Cells",
    "if (any(!cell_order %in% rownames(metadata))) stop('Expression cells are absent from metadata')",
    "metadata <- metadata[cell_order, , drop = FALSE]",
    "obj <- CreateSeuratObject(counts = counts, meta.data = metadata, assay = 'RNA')",
    "if (!identical(colnames(obj), cell_order)) stop('Layered Seurat object changed the released cell order')",
    "if ('CellType' %in% colnames(metadata)) Idents(obj) <- 'CellType'",
    "",
    "add_reduction <- function(obj, file, key, name) {",
    "  if (!file.exists(file)) return(obj)",
    "  emb <- as.data.frame(fread(file, sep = '\\t', check.names = FALSE, nThread = 4))",
    "  rownames(emb) <- emb$cell_id",
    "  emb$cell_id <- NULL",
    "  emb <- as.matrix(emb[colnames(obj), , drop = FALSE])",
    "  colnames(emb) <- paste0(key, seq_len(ncol(emb)))",
    "  obj[[name]] <- CreateDimReducObject(embeddings = emb, key = key, assay = DefaultAssay(obj))",
    "  obj",
    "}",
    "reduction_files <- c(unintegrated_pca='RAWPC_', scvi='SCVI_', harmony='HARMONY_', integrated_pca='IRPCA_', unintegrated_umap='RAWUMAP_', scvi_umap='SCVIUMAP_', harmony_umap='HARMONYUMAP_', integrated_umap='UMAP_')",
    "for (name in names(reduction_files)) obj <- add_reduction(obj, file.path(package_dir, 'embeddings', paste0(name, '.tsv.gz')), reduction_files[[name]], name)",
    "if (!is.na(output_file)) saveRDS(obj, output_file) else print(obj)"
  )
}

sciencedb_read_h5ad_lines <- function() {
  c(
    "#!/usr/bin/env python3",
    "from pathlib import Path",
    "import argparse",
    "import pandas as pd",
    "import scanpy as sc",
    "",
    "def load_brainomics_shards(package_dir, datasets=None):",
    "    package_dir = Path(package_dir).resolve()",
    "    expr_dir = package_dir / 'expression'",
    "    manifest = pd.read_csv(expr_dir / 'shard_manifest.tsv', sep='\\t')",
    "    if manifest['Dataset'].duplicated().any():",
    "        raise ValueError('Expression shard manifest has duplicated datasets')",
    "    if datasets is not None:",
    "        unknown = sorted(set(datasets) - set(manifest['Dataset']))",
    "        if unknown:",
    "            raise ValueError(f'Unknown dataset(s): {unknown}')",
    "        manifest = manifest.set_index('Dataset').loc[datasets].reset_index()",
    "    metadata = pd.read_csv(package_dir / 'metadata' / 'metadata.tsv.gz', sep='\\t').set_index('Cells')",
    "    embeddings = {}",
    "    for name in ['unintegrated_pca', 'scvi', 'harmony', 'integrated_pca', 'unintegrated_umap', 'scvi_umap', 'harmony_umap', 'integrated_umap']:",
    "        key = 'X_' + name",
    "        path = package_dir / 'embeddings' / f'{name}.tsv.gz'",
    "        if path.exists():",
    "            embeddings[key] = pd.read_csv(path, sep='\\t').set_index('cell_id')",
    "    result = {}",
    "    for row in manifest.itertuples(index=False):",
    "        shard_dir = expr_dir / row.Relative_Directory",
    "        adata = sc.read_10x_mtx(shard_dir, var_names='gene_ids', make_unique=True)",
    "        if adata.n_obs != row.Cells or adata.n_vars != row.Features or adata.X.nnz != row.Nonzero_Values:",
    "            raise ValueError(f'Expression shard contract failed for {row.Dataset}')",
    "        adata.obs = metadata.loc[adata.obs_names].copy()",
    "        for key, frame in embeddings.items():",
    "            adata.obsm[key] = frame.loc[adata.obs_names].to_numpy()",
    "        adata.uns['BrainOmicsData_dataset'] = row.Dataset",
    "        result[row.Dataset] = adata",
    "    return result",
    "",
    "def main():",
    "    parser = argparse.ArgumentParser(description='Read complete BrainOmicsData expression shards without concatenating them')",
    "    parser.add_argument('package_dir')",
    "    parser.add_argument('output_dir', nargs='?')",
    "    parser.add_argument('--datasets', help='Comma-separated dataset identifiers; default is all')",
    "    args = parser.parse_args()",
    "    datasets = None if args.datasets is None else [x.strip() for x in args.datasets.split(',') if x.strip()]",
    "    adatas = load_brainomics_shards(args.package_dir, datasets)",
    "    if args.output_dir:",
    "        output_dir = Path(args.output_dir)",
    "        output_dir.mkdir(parents=True, exist_ok=True)",
    "        for dataset, adata in adatas.items():",
    "            adata.write_h5ad(output_dir / f'{dataset}.h5ad')",
    "    else:",
    "        for dataset, adata in adatas.items():",
    "            print(f'{dataset}\\t{adata.n_obs} cells\\t{adata.n_vars} features\\t{adata.X.nnz} nonzero values')",
    "",
    "if __name__ == '__main__':",
    "    main()"
  )
}

write_sciencedb_readers <- function(out_dir) {
  scripts_dir <- file.path(out_dir, "scripts")
  dir.create(scripts_dir, recursive = TRUE, showWarnings = FALSE)
  writeLines(
    sciencedb_read_seurat_lines(), file.path(scripts_dir, "read_seurat.R")
  )
  writeLines(
    sciencedb_read_h5ad_lines(), file.path(scripts_dir, "read_h5ad.py")
  )
}

sciencedb_readme_lines <- function() {
  c(
    "# A human brain single-cell and single-nucleus transcriptomic resource across age intervals",
    "",
    "This package provides a directly reusable release of an integrated human brain scRNA-seq and snRNA-seq resource across age intervals.",
    "",
    "## Contents",
    "",
    "- `expression/shard_manifest.tsv`: ordered expression-shard inventory with dataset, dimensions, nonzero values and cell offsets.",
    "- `expression/shards/<dataset>/matrix.mtx.gz`, `features.tsv.gz` and `barcodes.tsv.gz`: complete dataset-resolved 10X-compatible raw-count matrices. Every released cell occurs in exactly one shard; no sampling is applied.",
    "- `metadata/metadata.tsv.gz`: 15-column cell-level metadata with source IDs, donor-sample-library hierarchy, harmonized age and region, source annotation, cluster and broad cell type.",
    "- `metadata/dataset_summary.tsv`: source accession and citation fields, first author, access status, original file type, expression units, genome/transcriptome build, modality, platform and chemistry.",
    "- `metadata/dataset_attrition_summary.tsv`: mutually exclusive per-dataset cell attrition categories from the complete processed source object through final export, plus the feature-selection boundary.",
    "- `metadata/verification_status_dictionary.tsv`: controlled definitions for verified, source-reported, derived, curated, unresolved, excluded and not-applicable evidence states.",
    "- `metadata/feature_metadata.tsv`: released feature identifiers, symbols and feature type.",
    "- `metadata/sample_schema_audit.tsv`: donor, biological-sample and library-count audit by source dataset.",
    "- `metadata/source_dataset_summary.tsv`, `metadata/age_interval_summary.tsv` and `metadata/main_celltype_summary.tsv`: release-level source, age and broad-cell-class summaries.",
    "- `embeddings/integrated_pca.tsv.gz` and `embeddings/integrated_umap.tsv.gz`: RPCA-integrated PCA and UMAP coordinates.",
    "- `embeddings/unintegrated_umap.tsv.gz`: pre-integration UMAP coordinates used for integration comparison.",
    "- `validation/lisi.tsv.gz`: per-cell dataset-label LISI values for Raw PCA, scVI, Harmony and RPCA in latent/integration space.",
    "- `validation/`: donor-aware integration metrics, seed stability, source-label concordance, independent held-out mapping with uncertainty, positive and exclusion-marker evidence, and the prespecified expression-context reuse analysis.",
    "- `objects/objects_celltype_plot.rds`: lightweight Seurat object for plotting, metadata inspection and cell-type annotation reuse.",
    "- `scripts/read_seurat.R`: reads selected shards or all shards as a Seurat v5 multi-layer assay without joining the count layers.",
    "- `scripts/read_h5ad.py`: reads selected shards into a dataset-keyed collection of AnnData objects and optionally writes one H5AD per dataset; it does not silently concatenate the full matrix.",
    "- `provenance/dataset_manifest.tsv`: source dataset counts, references, access, licence scope, redistribution status and mitochondrial-gene provenance.",
    "- `provenance/`: source-to-standard age, region, cell-type and technical-batch crosswalks; donor-specimen-library hierarchy; inclusion and attrition records; and source-overlap audits.",
    "- `provenance/environment/`: frozen preprocessing, integration, scVI and isolated held-out scop runtime records plus clean-room verification entry points.",
    "- `provenance/file_manifest.tsv` and `md5sum.txt`: every file with size, SHA256 and MD5, plus the checksum chain.",
    "",
    "The complete expression release is intentionally sharded because the combined count matrix contains more nonzero values than one R `dgCMatrix` can index. Each individual shard remains a complete `dgCMatrix`-compatible matrix. Sharding changes only storage layout: it does not sample cells, remove nonzero values or alter counts.",
    "",
    "The R reader accepts `Rscript scripts/read_seurat.R PACKAGE_DIR OUTPUT_RDS DATASET1,DATASET2`; omit the dataset argument or use `all` to read all shards. The Python reader accepts `python scripts/read_h5ad.py PACKAGE_DIR OUTPUT_DIR --datasets DATASET1,DATASET2`; by default it reads all shards and keeps them separate.",
    "",
    "The cell-level `Modality` field is standardized to `scRNA-seq` or `snRNA-seq`; `Technology` records the capture technology; `Sex` is standardized to `Female`, `Male` or `Not reported`. `Donor_ID`, `Sample_ID` and `Library_ID` preserve distinct biological and sequencing levels. `Original_Sample_ID` retains only source-published de-identified identifiers for traceability. Detailed platform and chemistry fields remain dataset-level because they are not uniformly cell-specific. Source-label provenance and curation rules are documented in the provenance crosswalks.",
    "",
    "The expression shards contain raw count values from Seurat count layers. `percent_ribo` is not exported because it cannot be reliably reconstructed for the current integrated object.",
    "",
    "The lightweight Seurat object in `objects/` is provided for convenient metadata, clustering, embedding and cell-type visualization workflows. It is not the full raw-count expression object; users requiring complete expression values should use the dataset-resolved shards in `expression/`."
  )
}

write_sciencedb_readme <- function(out_dir) {
  writeLines(sciencedb_readme_lines(), file.path(out_dir, "README.md"))
}
