#!/usr/bin/env Rscript
suppressPackageStartupMessages({library(Seurat);library(Matrix);library(jsonlite)})
a <- commandArgs(TRUE); stopifnot(length(a)==3L)
base<-normalizePath(a[1]); out<-normalizePath(a[2]); task<-as.integer(a[3])
settings<-data.frame(seed=c(20260730L,42L,2026L,20260730L,20260730L),resolution=c(2,2,2,1.5,2.5),role=c('baseline_replay','seed','seed','resolution','resolution'))
stopifnot(task %in% seq_len(nrow(settings)))
x<-settings[task,];run<-file.path(out,paste0('run_',task));dir.create(run,showWarnings=FALSE)
if(task>1L) stopifnot(file.exists(file.path(out,'run_1','BASELINE_REPLAY_PASS')))
gfile<-file.path(base,'integration_preview_20260917/rpca_symmetric_weighted_knn_graph.rds')
afile<-file.path(base,'integration_preview_20260917/cluster_assignments.rds')
sha<-function(p) unname(tools::md5sum(p))
old<-readRDS(afile);g<-readRDS(gfile)
stopifnot(nrow(old)==2602031L,length(unique(old$Cluster))==75L,!anyDuplicated(old$Cell),is(g,'Graph'),identical(rownames(g),old$Cell),identical(colnames(g),old$Cell),isSymmetric(g),all(is.finite(g@x)),all(g@x>0))
write_json(list(task=task,settings=x,cells=nrow(old),graph=gfile,graph_md5=sha(gfile),baseline_md5=sha(afile),algorithm=1,n_start=10,n_iter=10,group_singletons=TRUE,subsampling=FALSE,formal_annotation_modified=FALSE,scope='Clustering perturbation on the fixed full-cohort graph; not integration-seed or biological annotation validation'),file.path(run,'contract.json'),pretty=TRUE,auto_unbox=TRUE)
writeLines(capture.output(sessionInfo()),file.path(run,'sessionInfo.txt'))
future::plan('sequential');set.seed(x$seed);t0<-Sys.time()
z<-FindClusters(g,algorithm=1L,resolution=x$resolution,n.start=10L,n.iter=10L,random.seed=x$seed,group.singletons=TRUE,verbose=TRUE)
lab<-paste0('C',as.character(z[[1]]));stopifnot(length(lab)==nrow(old),!anyNA(lab));rm(g,z);gc()
tab<-table(Baseline=old$Cluster,Perturbed=lab);n<-sum(tab);choose2<-function(v) v*(v-1)/2
sa<-sum(choose2(rowSums(tab)));sb<-sum(choose2(colSums(tab)));s<-sum(choose2(tab));expected<-sa*sb/choose2(n);ari<-(s-expected)/((sa+sb)/2-expected)
summary<-data.frame(Task=task,Seed=x$seed,Resolution=x$resolution,Role=x$role,Cells=n,Clusters=length(unique(lab)),ARI=ari,Seconds=as.numeric(difftime(Sys.time(),t0,units='secs')))
write.table(summary,file.path(run,'summary.tsv'),sep='\t',quote=FALSE,row.names=FALSE)
counts<-as.data.frame(tab);counts<-counts[counts$Freq>0,];write.table(counts,file.path(run,'overlap.tsv'),sep='\t',quote=FALSE,row.names=FALSE)
metrics<-do.call(rbind,lapply(rownames(tab),function(k){ov<-tab[k,];sz<-sum(ov);data.frame(Baseline=k,Cells=sz,Largest_Fragment_Fraction=max(ov)/sz,Best_Jaccard=max(ov/(sz+colSums(tab)-ov)),Fragments=sum(ov>0))}))
write.table(metrics,file.path(run,'cluster_stability.tsv'),sep='\t',quote=FALSE,row.names=FALSE)
saveRDS(data.frame(Cell=old$Cell,Cluster=lab),file.path(run,'assignments.rds'),compress='gzip')
if(task==1L){stopifnot(ari>1-1e-12);writeLines('Partition replay matches frozen original assignments up to label permutation',file.path(run,'BASELINE_REPLAY_PASS'))}
write_json(list(state='COMPLETE',cells=n,task=task,ARI=ari,completed=as.character(Sys.time())),file.path(run,'COMPLETE.json'),pretty=TRUE,auto_unbox=TRUE)
