suppressPackageStartupMessages({library(data.table);library(Matrix);library(SeuratObject);library(jsonlite)})
setDTthreads(4);root<-normalizePath(commandArgs(TRUE)[1]);run<-file.path(root,'07_downstream/revision_20260918');p<-commandArgs(TRUE)[2];out<-file.path(p,'tables/age_signal');dir.create(out,recursive=TRUE,showWarnings=FALSE);m<-as.data.table(readRDS(file.path(p,'tables/metadata_formal.rds')))
elig<-!is.na(m$Global_Donor_ID)&nzchar(m$Global_Donor_ID)&!grepl('unknown',m$Donor_ID_Verification_Status,ignore.case=TRUE)&is.finite(m$Age_num)&is.finite(m$Age_Lower)&is.finite(m$Age_Upper)&m$Age_Lower==m$Age_Upper&m$Age_num==m$Age_Lower&!grepl('mean|midpoint|range',paste(m$Age_Representative_Method,m$Age),ignore.case=TRUE)&!m$Dataset%in%c('GSE178175','GSE144136')
if('Continuous_Age_Eligibility'%in%names(m))elig<-elig&!grepl('not eligible|mean|midpoint|range',m$Continuous_Age_Eligibility,ignore.case=TRUE)
elig[is.na(elig)]<-FALSE;m[,eligible:=elig];conf<-m[eligible==TRUE,.(Ages=uniqueN(paste(Age_num,Unit))),by=Canonical_Donor_ID];m[Canonical_Donor_ID%in%conf[Ages!=1,Canonical_Donor_ID],eligible:=FALSE];fwrite(conf[Ages!=1],file.path(out,'donor_age_conflicts.tsv'),sep='\t');fwrite(m[,.(Cells=.N),by=.(Dataset,Unit,eligible)],file.path(out,'age_eligibility.tsv'),sep='\t')
# Same prespecified frontal excitatory cohort as the previous analysis method; no search over outcomes.
sel<-which(m$eligible&m$Working_CellType=='Excitatory neurons'&m$BrainRegion=='Frontal cortex'&m$Unit=='Years');z<-m[sel];z[,group:=paste(Dataset,Canonical_Donor_ID,sep='|')];d<-z[,.(Dataset=Dataset[1],Canonical_Donor_ID=Canonical_Donor_ID[1],Cells=.N,Age=Age_num[1]),by=group][Cells>=20];z<-z[group%in%d$group];sel<-match(z$Cells,m$Cells);stopifnot(!anyNA(sel));I<-sparseMatrix(i=seq_along(sel),j=match(z$group,d$group),x=1/d$Cells[match(z$group,d$group)],dims=c(length(sel),nrow(d)));fwrite(d,file.path(out,'donor_metadata.tsv'),sep='\t')
m[,All_Donor_Group:=paste(Dataset,Canonical_Donor_ID,sep='|')];ad<-m[,.(Dataset=Dataset[1],Canonical_Donor_ID=Canonical_Donor_ID[1],Cells=.N),by=All_Donor_Group];J<-sparseMatrix(i=seq_len(nrow(m)),j=match(m$All_Donor_Group,ad$All_Donor_Group),x=1/ad$Cells[match(m$All_Donor_Group,ad$All_Donor_Group)],dims=c(nrow(m),nrow(ad)))
methods<-c(Raw='pca',RPCA='integrated.rpca',Harmony='integrated.harmony',scVI='integrated.scvi');cent<-allcent<-list()
for(method in names(methods)){e<-readRDS(file.path(root,'00_input_audit/compact',paste0('embedding_',methods[[method]],'.rds')));stopifnot(identical(m$Cells,rownames(e)),ncol(e)==50L);cent[[method]]<-as.matrix(crossprod(I,e[sel,,drop=FALSE]));allcent[[method]]<-as.matrix(crossprod(J,e));rm(e);gc(FALSE);message(Sys.time(),' centroids ',method)}
rm(I,J);gc(FALSE);saveRDS(list(donors=d,centroids=cent,all_donors=ad,all_centroids=allcent),file.path(out,'donor_centroids.rds'))
pred<-folds<-list()
for(study in unique(d$Dataset)){
 testall<-which(d$Dataset==study);train<-which(d$Dataset!=study & !d$Canonical_Donor_ID%in%d$Canonical_Donor_ID[testall]);test<-if(length(train))testall[d$Age[testall]>=min(d$Age[train]) & d$Age[testall]<=max(d$Age[train])]else integer();ok<-length(train)>=10L&&length(test)>=5L&&uniqueN(d$Age[test])>=3L
 folds[[study]]<-data.table(Dataset=study,Train_Donors=length(train),Test_Donors=length(test),Outside_Training_Range=length(testall)-length(test),Included=ok);if(!ok)next
 for(method in names(cent)){
  e<-cent[[method]];nr<-sqrt(rowSums(e^2));for(metric in c('euclidean','cosine')){
   dm<-if(metric=='euclidean')outer(nr[test]^2,nr[train]^2,'+')-2*tcrossprod(e[test,,drop=FALSE],e[train,,drop=FALSE]) else 1-tcrossprod((e/nr)[test,,drop=FALSE],(e/nr)[train,,drop=FALSE]);pr<-apply(dm,1,function(v)median(d$Age[train][order(v)[1:5]]));pred[[paste(study,method,metric)]]<-data.table(Dataset=study,Donor=d$Canonical_Donor_ID[test],Method=method,Distance=metric,Age=d$Age[test],Predicted_Age=pr,Median_Baseline=median(d$Age[train]))
  }
 }
}
fwrite(rbindlist(folds),file.path(out,'heldout_fold_coverage.tsv'),sep='\t');p<-rbindlist(pred);if(nrow(p)){p[,`:=`(Absolute_Error=abs(Age-Predicted_Age),Baseline_Error=abs(Age-Median_Baseline))];fwrite(p,file.path(out,'age_predictions.tsv'),sep='\t');ds<-p[,.(Donors=.N,MAE=mean(Absolute_Error),Baseline_MAE=mean(Baseline_Error),Spearman=suppressWarnings(cor(Age,Predicted_Age,method='spearman'))),by=.(Dataset,Method,Distance)];fwrite(ds,file.path(out,'age_metrics_by_dataset.tsv'),sep='\t');fwrite(ds[,.(Datasets=.N,Donors=sum(Donors),Dataset_Equal_MAE=mean(MAE),Dataset_Equal_Baseline_MAE=mean(Baseline_MAE)),by=.(Method,Distance)],file.path(out,'age_metrics_summary.tsv'),sep='\t')}
struc<-list();for(ds in unique(ad$Dataset)){ii<-which(ad$Dataset==ds);if(length(ii)<4)next;raw<-as.vector(dist(allcent$Raw[ii,,drop=FALSE]));for(method in names(allcent))struc[[paste(ds,method)]]<-data.table(Dataset=ds,Donors=length(ii),Method=method,Spearman_Donor_Distance_to_Raw=suppressWarnings(cor(raw,as.vector(dist(allcent[[method]][ii,,drop=FALSE])),method='spearman')))};fwrite(rbindlist(struc),file.path(out,'donor_structure_by_dataset.tsv'),sep='\t')
write_json(list(state='COMPLETE',cells_in_donor_structure=nrow(m),age_cohort_cells=nrow(z),age_cohort_donors=nrow(d),test_predictions=nrow(p),sampling=FALSE,bootstrap=FALSE,permutation=FALSE,simulation=FALSE,cohort='Prespecified frontal excitatory neurons, exact postnatal ages; >=20 cells/donor',validation='Leave-one-study-out, exclude shared canonical donors from training, k=5 median, >=10 training and >=5 interpolation test donors with >=3 ages',limits='Fixed integrated representations are transductive; descriptive point estimates without resampling intervals. Donor-distance pairs are not treated as independent replicates.'),file.path(out,'COMPLETE.json'),auto_unbox=TRUE,pretty=TRUE);message(Sys.time(),' COMPLETE')
